name: Update README Cards

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate stats
        run: |
          mkdir -p profile
          curl -L -o profile/stats.svg "https://github-readme-stats.vercel.app/api?username=Dippp10&show_icons=true"

      - name: Commit file
        run: |
          git config --global user.name "Dippp10"
          git config --global user.email "deepikakarthik697@gmail.com"
          git add .
          git commit -m "Update README cards" || echo "No changes"

      - name: Push
        run: |
          git push
