name: Update README Stats

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create profile folder
        run: mkdir -p profile

      - name: Generate GitHub stats SVG
        run: |
          curl -L -o profile/stats.svg "https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?username=Dippp10&show_icons=true&theme=radical"

      - name: Commit changes
        run: |
          git config --global user.name "Dippp10"
          git config --global user.email "deepikakarthik697@gmail.com"
          git add profile/stats.svg
          git commit -m "Update README stats" || echo "No changes to commit"

      - name: Push changes
        run: git push
